name: Generate gRPC Code

on:
  push:
    branches:
      - main
    paths:
      - 'proto/**/*.proto'
      - 'buf.yaml'
      - 'buf.gen.yaml'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - 'proto/**/*.proto'
      - 'buf.yaml'
      - 'buf.gen.yaml'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: 'latest'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'

      - name: Install protoc plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest

      - name: Buf dep update
        run: buf dep update

      - name: Buf lint
        run: buf lint

      - name: Fetch repository history
        if: github.event_name == 'pull_request'
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: Buf breaking change detection
        if: github.event_name == 'pull_request'
        continue-on-error: true # Временно, пока в main не появится buf.lock
        run: buf breaking --against '.git#branch=origin/main'

      - name: Generate code
        run: buf generate

      - name: Commit and push generated code
        if: github.event_name == 'push'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add gen/ docs/ buf.lock
          if git diff --staged --quiet; then
            echo "No changes in generated code"
          else
            git commit -m "chore: regenerate proto code [skip ci]"
            git push
          fi

